version: '3'
services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./database
    user: postgres
    environment:
      POSTGRES_DB: crux_db
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/src
    depends_on:
      db:
        condition: service_healthy
        restart: true
  
  web:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - server